"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_generated
from auth_generated.model.auth_auth_request import AuthAuthRequest


class TestAuthAuthRequest(unittest.TestCase):
    """AuthAuthRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthAuthRequest(self):
        """Test AuthAuthRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthAuthRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
