"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import auth_generated
from auth_generated.api.key_service_api import KeyServiceApi  # noqa: E501


class TestKeyServiceApi(unittest.TestCase):
    """KeyServiceApi unit test stubs"""

    def setUp(self):
        self.api = KeyServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_key_service_get_key(self):
        """Test case for key_service_get_key

        """
        pass


if __name__ == '__main__':
    unittest.main()
