"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_generated
from auth_generated.model.auth_auth_response import AuthAuthResponse


class TestAuthAuthResponse(unittest.TestCase):
    """AuthAuthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthAuthResponse(self):
        """Test AuthAuthResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthAuthResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
