"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.snapshot_snapshot import SnapshotSnapshot
globals()['SnapshotSnapshot'] = SnapshotSnapshot
from vps_generated.model.snapshot_edit_response import SnapshotEditResponse


class TestSnapshotEditResponse(unittest.TestCase):
    """SnapshotEditResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotEditResponse(self):
        """Test SnapshotEditResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SnapshotEditResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
