"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_stop_vps_response_error import ManageStopVpsResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageStopVpsResponseError'] = ManageStopVpsResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_stop_vps_response import ManageStopVpsResponse


class TestManageStopVpsResponse(unittest.TestCase):
    """ManageStopVpsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageStopVpsResponse(self):
        """Test ManageStopVpsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageStopVpsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
