"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_check_software_requirements_response_error import ManageCheckSoftwareRequirementsResponseError
globals()['ManageCheckSoftwareRequirementsResponseError'] = ManageCheckSoftwareRequirementsResponseError
from vps_generated.model.manage_check_software_requirements_response import ManageCheckSoftwareRequirementsResponse


class TestManageCheckSoftwareRequirementsResponse(unittest.TestCase):
    """ManageCheckSoftwareRequirementsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageCheckSoftwareRequirementsResponse(self):
        """Test ManageCheckSoftwareRequirementsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageCheckSoftwareRequirementsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
