"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_software_install_info import ManageSoftwareInstallInfo
globals()['ManageSoftwareInstallInfo'] = ManageSoftwareInstallInfo
from vps_generated.model.manage_check_software_requirements_request import ManageCheckSoftwareRequirementsRequest


class TestManageCheckSoftwareRequirementsRequest(unittest.TestCase):
    """ManageCheckSoftwareRequirementsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageCheckSoftwareRequirementsRequest(self):
        """Test ManageCheckSoftwareRequirementsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageCheckSoftwareRequirementsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
