"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.structures_operating_system_requirements import StructuresOperatingSystemRequirements
globals()['StructuresOperatingSystemRequirements'] = StructuresOperatingSystemRequirements
from vps_generated.model.structures_operating_system import StructuresOperatingSystem


class TestStructuresOperatingSystem(unittest.TestCase):
    """StructuresOperatingSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStructuresOperatingSystem(self):
        """Test StructuresOperatingSystem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StructuresOperatingSystem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
