"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_stop_rescue_response_error import ManageStopRescueResponseError


class TestManageStopRescueResponseError(unittest.TestCase):
    """ManageStopRescueResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageStopRescueResponseError(self):
        """Test ManageStopRescueResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageStopRescueResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
