"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import vps_generated
from vps_generated.api.backup_service_api import BackupServiceApi  # noqa: E501


class TestBackupServiceApi(unittest.TestCase):
    """BackupServiceApi unit test stubs"""

    def setUp(self):
        self.api = BackupServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_backup_service_get_available_copies(self):
        """Test case for backup_service_get_available_copies

        """
        pass

    def test_backup_service_get_backup_file_list(self):
        """Test case for backup_service_get_backup_file_list

        """
        pass

    def test_backup_service_get_orders(self):
        """Test case for backup_service_get_orders

        """
        pass

    def test_backup_service_restore_file(self):
        """Test case for backup_service_restore_file

        """
        pass

    def test_backup_service_restore_server(self):
        """Test case for backup_service_restore_server

        """
        pass


if __name__ == '__main__':
    unittest.main()
