"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_detach_ssh_key_response_error import ManageDetachSshKeyResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageDetachSshKeyResponseError'] = ManageDetachSshKeyResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_detach_ssh_key_response import ManageDetachSshKeyResponse


class TestManageDetachSshKeyResponse(unittest.TestCase):
    """ManageDetachSshKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageDetachSshKeyResponse(self):
        """Test ManageDetachSshKeyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageDetachSshKeyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
