"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.structures_private_network import StructuresPrivateNetwork


class TestStructuresPrivateNetwork(unittest.TestCase):
    """StructuresPrivateNetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStructuresPrivateNetwork(self):
        """Test StructuresPrivateNetwork"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StructuresPrivateNetwork()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
