"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_history_item import ManageHistoryItem
globals()['ManageHistoryItem'] = ManageHistoryItem
from vps_generated.model.manage_get_history_response import ManageGetHistoryResponse


class TestManageGetHistoryResponse(unittest.TestCase):
    """ManageGetHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageGetHistoryResponse(self):
        """Test ManageGetHistoryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageGetHistoryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
