"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.structures_copy_info import StructuresCopyInfo
globals()['StructuresCopyInfo'] = StructuresCopyInfo
from vps_generated.model.backup_get_available_copies_response import BackupGetAvailableCopiesResponse


class TestBackupGetAvailableCopiesResponse(unittest.TestCase):
    """BackupGetAvailableCopiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackupGetAvailableCopiesResponse(self):
        """Test BackupGetAvailableCopiesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BackupGetAvailableCopiesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
