"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_create_vps_response_error_software_variable_error import ManageCreateVpsResponseErrorSoftwareVariableError


class TestManageCreateVpsResponseErrorSoftwareVariableError(unittest.TestCase):
    """ManageCreateVpsResponseErrorSoftwareVariableError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageCreateVpsResponseErrorSoftwareVariableError(self):
        """Test ManageCreateVpsResponseErrorSoftwareVariableError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageCreateVpsResponseErrorSoftwareVariableError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
