"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.snapshot_create_calculator_response import SnapshotCreateCalculatorResponse


class TestSnapshotCreateCalculatorResponse(unittest.TestCase):
    """SnapshotCreateCalculatorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotCreateCalculatorResponse(self):
        """Test SnapshotCreateCalculatorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SnapshotCreateCalculatorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
