"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_get_installed_software_response_installed_software_info import ManageGetInstalledSoftwareResponseInstalledSoftwareInfo
globals()['ManageGetInstalledSoftwareResponseInstalledSoftwareInfo'] = ManageGetInstalledSoftwareResponseInstalledSoftwareInfo
from vps_generated.model.manage_get_installed_software_response import ManageGetInstalledSoftwareResponse


class TestManageGetInstalledSoftwareResponse(unittest.TestCase):
    """ManageGetInstalledSoftwareResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageGetInstalledSoftwareResponse(self):
        """Test ManageGetInstalledSoftwareResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageGetInstalledSoftwareResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
