"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.snapshot_remove_response_error import SnapshotRemoveResponseError
from vps_generated.model.snapshot_snapshot import SnapshotSnapshot
globals()['SnapshotRemoveResponseError'] = SnapshotRemoveResponseError
globals()['SnapshotSnapshot'] = SnapshotSnapshot
from vps_generated.model.snapshot_remove_response import SnapshotRemoveResponse


class TestSnapshotRemoveResponse(unittest.TestCase):
    """SnapshotRemoveResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotRemoveResponse(self):
        """Test SnapshotRemoveResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SnapshotRemoveResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
