"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_reboot_vps_response_error import ManageRebootVpsResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageRebootVpsResponseError'] = ManageRebootVpsResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_reboot_vps_response import ManageRebootVpsResponse


class TestManageRebootVpsResponse(unittest.TestCase):
    """ManageRebootVpsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageRebootVpsResponse(self):
        """Test ManageRebootVpsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageRebootVpsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
