"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import vps_generated
from vps_generated.api.snapshot_service_api import SnapshotServiceApi  # noqa: E501


class TestSnapshotServiceApi(unittest.TestCase):
    """SnapshotServiceApi unit test stubs"""

    def setUp(self):
        self.api = SnapshotServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_snapshot_service_create(self):
        """Test case for snapshot_service_create

        """
        pass

    def test_snapshot_service_create_calculator(self):
        """Test case for snapshot_service_create_calculator

        """
        pass

    def test_snapshot_service_edit(self):
        """Test case for snapshot_service_edit

        """
        pass

    def test_snapshot_service_get_all(self):
        """Test case for snapshot_service_get_all

        """
        pass

    def test_snapshot_service_get_all_restores(self):
        """Test case for snapshot_service_get_all_restores

        """
        pass

    def test_snapshot_service_remove(self):
        """Test case for snapshot_service_remove

        """
        pass

    def test_snapshot_service_restore(self):
        """Test case for snapshot_service_restore

        """
        pass


if __name__ == '__main__':
    unittest.main()
