"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.statistic_series_data import StatisticSeriesData
globals()['StatisticSeriesData'] = StatisticSeriesData
from vps_generated.model.statistic_get_cpu_response import StatisticGetCpuResponse


class TestStatisticGetCpuResponse(unittest.TestCase):
    """StatisticGetCpuResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatisticGetCpuResponse(self):
        """Test StatisticGetCpuResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatisticGetCpuResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
