"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.structures_ssh_key_info import StructuresSshKeyInfo
globals()['StructuresSshKeyInfo'] = StructuresSshKeyInfo
from vps_generated.model.ssh_key_get_all_response import SshKeyGetAllResponse


class TestSshKeyGetAllResponse(unittest.TestCase):
    """SshKeyGetAllResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSshKeyGetAllResponse(self):
        """Test SshKeyGetAllResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SshKeyGetAllResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
