"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.ssh_key_add_response_error import SshKeyAddResponseError


class TestSshKeyAddResponseError(unittest.TestCase):
    """SshKeyAddResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSshKeyAddResponseError(self):
        """Test SshKeyAddResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SshKeyAddResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
