"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import vps_generated
from vps_generated.api.ssh_key_service_api import SshKeyServiceApi  # noqa: E501


class TestSshKeyServiceApi(unittest.TestCase):
    """SshKeyServiceApi unit test stubs"""

    def setUp(self):
        self.api = SshKeyServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ssh_key_service_add(self):
        """Test case for ssh_key_service_add

        """
        pass

    def test_ssh_key_service_get_all(self):
        """Test case for ssh_key_service_get_all

        """
        pass

    def test_ssh_key_service_remove(self):
        """Test case for ssh_key_service_remove

        """
        pass


if __name__ == '__main__':
    unittest.main()
