"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.snapshot_restore import SnapshotRestore
from vps_generated.model.snapshot_restore_response_error import SnapshotRestoreResponseError
globals()['SnapshotRestore'] = SnapshotRestore
globals()['SnapshotRestoreResponseError'] = SnapshotRestoreResponseError
from vps_generated.model.snapshot_restore_response import SnapshotRestoreResponse


class TestSnapshotRestoreResponse(unittest.TestCase):
    """SnapshotRestoreResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotRestoreResponse(self):
        """Test SnapshotRestoreResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SnapshotRestoreResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
