"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.statistic_get_process_list_response_error import StatisticGetProcessListResponseError
from vps_generated.model.statistic_get_process_list_response_process_list import StatisticGetProcessListResponseProcessList
globals()['StatisticGetProcessListResponseError'] = StatisticGetProcessListResponseError
globals()['StatisticGetProcessListResponseProcessList'] = StatisticGetProcessListResponseProcessList
from vps_generated.model.statistic_get_process_list_response import StatisticGetProcessListResponse


class TestStatisticGetProcessListResponse(unittest.TestCase):
    """StatisticGetProcessListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatisticGetProcessListResponse(self):
        """Test StatisticGetProcessListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatisticGetProcessListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
