"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_vps_configuration import ManageVpsConfiguration
from vps_generated.model.structures_attached_private_network import StructuresAttachedPrivateNetwork
from vps_generated.model.structures_operating_system import StructuresOperatingSystem
from vps_generated.model.structures_ssh_key_info import StructuresSshKeyInfo
globals()['ManageVpsConfiguration'] = ManageVpsConfiguration
globals()['StructuresAttachedPrivateNetwork'] = StructuresAttachedPrivateNetwork
globals()['StructuresOperatingSystem'] = StructuresOperatingSystem
globals()['StructuresSshKeyInfo'] = StructuresSshKeyInfo
from vps_generated.model.manage_vps_info import ManageVpsInfo


class TestManageVpsInfo(unittest.TestCase):
    """ManageVpsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageVpsInfo(self):
        """Test ManageVpsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageVpsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
