"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import vps_generated
from vps_generated.api.manage_service_api import ManageServiceApi  # noqa: E501


class TestManageServiceApi(unittest.TestCase):
    """ManageServiceApi unit test stubs"""

    def setUp(self):
        self.api = ManageServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_manage_service_attach_ip_address(self):
        """Test case for manage_service_attach_ip_address

        """
        pass

    def test_manage_service_attach_ssh_key(self):
        """Test case for manage_service_attach_ssh_key

        """
        pass

    def test_manage_service_attach_to_private_network(self):
        """Test case for manage_service_attach_to_private_network

        """
        pass

    def test_manage_service_change_configuration(self):
        """Test case for manage_service_change_configuration

        """
        pass

    def test_manage_service_change_ssh_access(self):
        """Test case for manage_service_change_ssh_access

        """
        pass

    def test_manage_service_check_software_requirements(self):
        """Test case for manage_service_check_software_requirements

        """
        pass

    def test_manage_service_create_vps(self):
        """Test case for manage_service_create_vps

        """
        pass

    def test_manage_service_detach_from_private_network(self):
        """Test case for manage_service_detach_from_private_network

        """
        pass

    def test_manage_service_detach_ip_address(self):
        """Test case for manage_service_detach_ip_address

        """
        pass

    def test_manage_service_detach_ssh_key(self):
        """Test case for manage_service_detach_ssh_key

        """
        pass

    def test_manage_service_get_available_configuration(self):
        """Test case for manage_service_get_available_configuration

        """
        pass

    def test_manage_service_get_available_software(self):
        """Test case for manage_service_get_available_software

        """
        pass

    def test_manage_service_get_file_manager_settings(self):
        """Test case for manage_service_get_file_manager_settings

        """
        pass

    def test_manage_service_get_history(self):
        """Test case for manage_service_get_history

        """
        pass

    def test_manage_service_get_info(self):
        """Test case for manage_service_get_info

        """
        pass

    def test_manage_service_get_installed_software(self):
        """Test case for manage_service_get_installed_software

        """
        pass

    def test_manage_service_get_list(self):
        """Test case for manage_service_get_list

        """
        pass

    def test_manage_service_get_statuses(self):
        """Test case for manage_service_get_statuses

        """
        pass

    def test_manage_service_reboot_vps(self):
        """Test case for manage_service_reboot_vps

        """
        pass

    def test_manage_service_reinstall(self):
        """Test case for manage_service_reinstall

        """
        pass

    def test_manage_service_remove_vps(self):
        """Test case for manage_service_remove_vps

        """
        pass

    def test_manage_service_reset_password(self):
        """Test case for manage_service_reset_password

        """
        pass

    def test_manage_service_reset_vps(self):
        """Test case for manage_service_reset_vps

        """
        pass

    def test_manage_service_start_rescue(self):
        """Test case for manage_service_start_rescue

        """
        pass

    def test_manage_service_start_vps(self):
        """Test case for manage_service_start_vps

        """
        pass

    def test_manage_service_stop_rescue(self):
        """Test case for manage_service_stop_rescue

        """
        pass

    def test_manage_service_stop_vps(self):
        """Test case for manage_service_stop_vps

        """
        pass

    def test_manage_service_unarchive(self):
        """Test case for manage_service_unarchive

        """
        pass

    def test_manage_service_update_info(self):
        """Test case for manage_service_update_info

        """
        pass


if __name__ == '__main__':
    unittest.main()
