"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_attach_ip_address_response_error import ManageAttachIpAddressResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageAttachIpAddressResponseError'] = ManageAttachIpAddressResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_attach_ip_address_response import ManageAttachIpAddressResponse


class TestManageAttachIpAddressResponse(unittest.TestCase):
    """ManageAttachIpAddressResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageAttachIpAddressResponse(self):
        """Test ManageAttachIpAddressResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageAttachIpAddressResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
