"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_reinstall_response_error import ManageReinstallResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageReinstallResponseError'] = ManageReinstallResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_reinstall_response import ManageReinstallResponse


class TestManageReinstallResponse(unittest.TestCase):
    """ManageReinstallResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageReinstallResponse(self):
        """Test ManageReinstallResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageReinstallResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
