"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_get_available_software_response_software_info import ManageGetAvailableSoftwareResponseSoftwareInfo
globals()['ManageGetAvailableSoftwareResponseSoftwareInfo'] = ManageGetAvailableSoftwareResponseSoftwareInfo
from vps_generated.model.manage_get_available_software_response import ManageGetAvailableSoftwareResponse


class TestManageGetAvailableSoftwareResponse(unittest.TestCase):
    """ManageGetAvailableSoftwareResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageGetAvailableSoftwareResponse(self):
        """Test ManageGetAvailableSoftwareResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageGetAvailableSoftwareResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
