"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_attach_ssh_key_response_error import ManageAttachSshKeyResponseError


class TestManageAttachSshKeyResponseError(unittest.TestCase):
    """ManageAttachSshKeyResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageAttachSshKeyResponseError(self):
        """Test ManageAttachSshKeyResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageAttachSshKeyResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
