"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.ssh_key_remove_response_error import SshKeyRemoveResponseError


class TestSshKeyRemoveResponseError(unittest.TestCase):
    """SshKeyRemoveResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSshKeyRemoveResponseError(self):
        """Test SshKeyRemoveResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SshKeyRemoveResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
