"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.snapshot_restore import SnapshotRestore
globals()['SnapshotRestore'] = SnapshotRestore
from vps_generated.model.snapshot_get_all_restores_response import SnapshotGetAllRestoresResponse


class TestSnapshotGetAllRestoresResponse(unittest.TestCase):
    """SnapshotGetAllRestoresResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotGetAllRestoresResponse(self):
        """Test SnapshotGetAllRestoresResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SnapshotGetAllRestoresResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
