"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.structures_order_info_error_details_file_error import StructuresOrderInfoErrorDetailsFileError
globals()['StructuresOrderInfoErrorDetailsFileError'] = StructuresOrderInfoErrorDetailsFileError
from vps_generated.model.structures_order_info_error_details import StructuresOrderInfoErrorDetails


class TestStructuresOrderInfoErrorDetails(unittest.TestCase):
    """StructuresOrderInfoErrorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStructuresOrderInfoErrorDetails(self):
        """Test StructuresOrderInfoErrorDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StructuresOrderInfoErrorDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
