"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_generated
from auth_generated.model.key_get_key_response import KeyGetKeyResponse


class TestKeyGetKeyResponse(unittest.TestCase):
    """KeyGetKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyGetKeyResponse(self):
        """Test KeyGetKeyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KeyGetKeyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
