"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from vps_generated.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from vps_generated.exceptions import ApiAttributeError


def lazy_import():
    from vps_generated.model.manage_vps_configuration import ManageVpsConfiguration
    from vps_generated.model.structures_attached_private_network import StructuresAttachedPrivateNetwork
    from vps_generated.model.structures_operating_system import StructuresOperatingSystem
    from vps_generated.model.structures_ssh_key_info import StructuresSshKeyInfo
    globals()['ManageVpsConfiguration'] = ManageVpsConfiguration
    globals()['StructuresAttachedPrivateNetwork'] = StructuresAttachedPrivateNetwork
    globals()['StructuresOperatingSystem'] = StructuresOperatingSystem
    globals()['StructuresSshKeyInfo'] = StructuresSshKeyInfo


class ManageVpsInfo(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (str,),  # noqa: E501
            'slug': (str,),  # noqa: E501
            'display_name': (str,),  # noqa: E501
            'hostname': (str,),  # noqa: E501
            'configuration': (ManageVpsConfiguration,),  # noqa: E501
            'status': (str,),  # noqa: E501
            'ssh_keys': ([StructuresSshKeyInfo],),  # noqa: E501
            'has_password': (bool,),  # noqa: E501
            'manage_enabled': (bool,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'date_create': (str,),  # noqa: E501
            'operating_system': (StructuresOperatingSystem,),  # noqa: E501
            'ip_address': (str,),  # noqa: E501
            'rescue_mode': (bool,),  # noqa: E501
            'migrating': (bool,),  # noqa: E501
            'host_unavailable': (bool,),  # noqa: E501
            'unblocking': (bool,),  # noqa: E501
            'restoring': (bool,),  # noqa: E501
            'disk_used': (str,),  # noqa: E501
            'disk_left': (str,),  # noqa: E501
            'additional_ip_address': ([str],),  # noqa: E501
            'beget_ssh_access_allowed': (bool,),  # noqa: E501
            'archived': (bool,),  # noqa: E501
            'unarchiving': (bool,),  # noqa: E501
            'private_network': ([StructuresAttachedPrivateNetwork],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'slug': 'slug',  # noqa: E501
        'display_name': 'display_name',  # noqa: E501
        'hostname': 'hostname',  # noqa: E501
        'configuration': 'configuration',  # noqa: E501
        'status': 'status',  # noqa: E501
        'ssh_keys': 'ssh_keys',  # noqa: E501
        'has_password': 'has_password',  # noqa: E501
        'manage_enabled': 'manage_enabled',  # noqa: E501
        'description': 'description',  # noqa: E501
        'date_create': 'date_create',  # noqa: E501
        'operating_system': 'operating_system',  # noqa: E501
        'ip_address': 'ip_address',  # noqa: E501
        'rescue_mode': 'rescue_mode',  # noqa: E501
        'migrating': 'migrating',  # noqa: E501
        'host_unavailable': 'host_unavailable',  # noqa: E501
        'unblocking': 'unblocking',  # noqa: E501
        'restoring': 'restoring',  # noqa: E501
        'disk_used': 'disk_used',  # noqa: E501
        'disk_left': 'disk_left',  # noqa: E501
        'additional_ip_address': 'additional_ip_address',  # noqa: E501
        'beget_ssh_access_allowed': 'beget_ssh_access_allowed',  # noqa: E501
        'archived': 'archived',  # noqa: E501
        'unarchiving': 'unarchiving',  # noqa: E501
        'private_network': 'private_network',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """ManageVpsInfo - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): Идентификатор Vps (uuid). [optional]  # noqa: E501
            slug (str): ЧПУ-френдли имя Vps (может быть пустой строкой). [optional]  # noqa: E501
            display_name (str): Отображаемое имя Vps. [optional]  # noqa: E501
            hostname (str): Имя хоста (в ОС). [optional]  # noqa: E501
            configuration (ManageVpsConfiguration): [optional]  # noqa: E501
            status (str): Текущий статус Vps. [optional]  # noqa: E501
            ssh_keys ([StructuresSshKeyInfo]): Информация об ssh-ключах. [optional]  # noqa: E501
            has_password (bool): Возможен ли вход по паролю. [optional]  # noqa: E501
            manage_enabled (bool): Доступно ли управление данной Vps. [optional]  # noqa: E501
            description (str): Дескрипшн для пользователя. [optional]  # noqa: E501
            date_create (str): Дата создания (в формате W3C). [optional]  # noqa: E501
            operating_system (StructuresOperatingSystem): [optional]  # noqa: E501
            ip_address (str): Основной IP-адрес. [optional]  # noqa: E501
            rescue_mode (bool): Включен rescue-режим. [optional]  # noqa: E501
            migrating (bool): VPS находится в состоянии миграции на другой хост. [optional]  # noqa: E501
            host_unavailable (bool): Нет возможности получать информацию с хоста, на котором находится vps. [optional]  # noqa: E501
            unblocking (bool): VPS находится в состоянии разблокировки. [optional]  # noqa: E501
            restoring (bool): VPS находится в состоянии восстановления из резервной копии. [optional]  # noqa: E501
            disk_used (str): Занято места на главном разделе, Мб. [optional]  # noqa: E501
            disk_left (str): Осталось свободного места на главном разделе, Мб. [optional]  # noqa: E501
            additional_ip_address ([str]): Информация о дополнительных IP-адресах VPS. [optional]  # noqa: E501
            beget_ssh_access_allowed (bool): Согласие на доступ к пользовательской машине через SSH-ключи BeGet Необходимо для использования пользователем файлового менеджера. [optional]  # noqa: E501
            archived (bool): VPS заархивирована, управление невозможно. [optional]  # noqa: E501
            unarchiving (bool): VPS в процессе разархивации. [optional]  # noqa: E501
            private_network ([StructuresAttachedPrivateNetwork]): Приватные сети к которым подключена VPS. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ManageVpsInfo - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): Идентификатор Vps (uuid). [optional]  # noqa: E501
            slug (str): ЧПУ-френдли имя Vps (может быть пустой строкой). [optional]  # noqa: E501
            display_name (str): Отображаемое имя Vps. [optional]  # noqa: E501
            hostname (str): Имя хоста (в ОС). [optional]  # noqa: E501
            configuration (ManageVpsConfiguration): [optional]  # noqa: E501
            status (str): Текущий статус Vps. [optional]  # noqa: E501
            ssh_keys ([StructuresSshKeyInfo]): Информация об ssh-ключах. [optional]  # noqa: E501
            has_password (bool): Возможен ли вход по паролю. [optional]  # noqa: E501
            manage_enabled (bool): Доступно ли управление данной Vps. [optional]  # noqa: E501
            description (str): Дескрипшн для пользователя. [optional]  # noqa: E501
            date_create (str): Дата создания (в формате W3C). [optional]  # noqa: E501
            operating_system (StructuresOperatingSystem): [optional]  # noqa: E501
            ip_address (str): Основной IP-адрес. [optional]  # noqa: E501
            rescue_mode (bool): Включен rescue-режим. [optional]  # noqa: E501
            migrating (bool): VPS находится в состоянии миграции на другой хост. [optional]  # noqa: E501
            host_unavailable (bool): Нет возможности получать информацию с хоста, на котором находится vps. [optional]  # noqa: E501
            unblocking (bool): VPS находится в состоянии разблокировки. [optional]  # noqa: E501
            restoring (bool): VPS находится в состоянии восстановления из резервной копии. [optional]  # noqa: E501
            disk_used (str): Занято места на главном разделе, Мб. [optional]  # noqa: E501
            disk_left (str): Осталось свободного места на главном разделе, Мб. [optional]  # noqa: E501
            additional_ip_address ([str]): Информация о дополнительных IP-адресах VPS. [optional]  # noqa: E501
            beget_ssh_access_allowed (bool): Согласие на доступ к пользовательской машине через SSH-ключи BeGet Необходимо для использования пользователем файлового менеджера. [optional]  # noqa: E501
            archived (bool): VPS заархивирована, управление невозможно. [optional]  # noqa: E501
            unarchiving (bool): VPS в процессе разархивации. [optional]  # noqa: E501
            private_network ([StructuresAttachedPrivateNetwork]): Приватные сети к которым подключена VPS. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
