# flake8: noqa

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from vps_generated.api_client import ApiClient

# import Configuration
from vps_generated.configuration import Configuration

# import exceptions
from vps_generated.exceptions import OpenApiException
from vps_generated.exceptions import ApiAttributeError
from vps_generated.exceptions import ApiTypeError
from vps_generated.exceptions import ApiValueError
from vps_generated.exceptions import ApiKeyError
from vps_generated.exceptions import ApiException
