"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.network_create_private_network_response_error import NetworkCreatePrivateNetworkResponseError
from vps_generated.model.structures_private_network import StructuresPrivateNetwork
globals()['NetworkCreatePrivateNetworkResponseError'] = NetworkCreatePrivateNetworkResponseError
globals()['StructuresPrivateNetwork'] = StructuresPrivateNetwork
from vps_generated.model.network_create_private_network_response import NetworkCreatePrivateNetworkResponse


class TestNetworkCreatePrivateNetworkResponse(unittest.TestCase):
    """NetworkCreatePrivateNetworkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkCreatePrivateNetworkResponse(self):
        """Test NetworkCreatePrivateNetworkResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkCreatePrivateNetworkResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
