"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_software_install_info import ManageSoftwareInstallInfo
globals()['ManageSoftwareInstallInfo'] = ManageSoftwareInstallInfo
from vps_generated.model.manage_reinstall_request import ManageReinstallRequest


class TestManageReinstallRequest(unittest.TestCase):
    """ManageReinstallRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageReinstallRequest(self):
        """Test ManageReinstallRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageReinstallRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
