"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_stop_rescue_response_error import ManageStopRescueResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageStopRescueResponseError'] = ManageStopRescueResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_stop_rescue_response import ManageStopRescueResponse


class TestManageStopRescueResponse(unittest.TestCase):
    """ManageStopRescueResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageStopRescueResponse(self):
        """Test ManageStopRescueResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageStopRescueResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
