"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.structures_order_info import StructuresOrderInfo
globals()['StructuresOrderInfo'] = StructuresOrderInfo
from vps_generated.model.backup_get_orders_response import BackupGetOrdersResponse


class TestBackupGetOrdersResponse(unittest.TestCase):
    """BackupGetOrdersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackupGetOrdersResponse(self):
        """Test BackupGetOrdersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BackupGetOrdersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
