"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_private_network_info import ManagePrivateNetworkInfo
from vps_generated.model.manage_software_install_info import ManageSoftwareInstallInfo
globals()['ManagePrivateNetworkInfo'] = ManagePrivateNetworkInfo
globals()['ManageSoftwareInstallInfo'] = ManageSoftwareInstallInfo
from vps_generated.model.manage_create_vps_request import ManageCreateVpsRequest


class TestManageCreateVpsRequest(unittest.TestCase):
    """ManageCreateVpsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageCreateVpsRequest(self):
        """Test ManageCreateVpsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageCreateVpsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
