"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_get_available_software_response_software_info_requirements import ManageGetAvailableSoftwareResponseSoftwareInfoRequirements
globals()['ManageGetAvailableSoftwareResponseSoftwareInfoRequirements'] = ManageGetAvailableSoftwareResponseSoftwareInfoRequirements
from vps_generated.model.manage_get_available_software_response_software_info import ManageGetAvailableSoftwareResponseSoftwareInfo


class TestManageGetAvailableSoftwareResponseSoftwareInfo(unittest.TestCase):
    """ManageGetAvailableSoftwareResponseSoftwareInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageGetAvailableSoftwareResponseSoftwareInfo(self):
        """Test ManageGetAvailableSoftwareResponseSoftwareInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageGetAvailableSoftwareResponseSoftwareInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
