"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.snapshot_create_response_error import SnapshotCreateResponseError
from vps_generated.model.snapshot_snapshot import SnapshotSnapshot
globals()['SnapshotCreateResponseError'] = SnapshotCreateResponseError
globals()['SnapshotSnapshot'] = SnapshotSnapshot
from vps_generated.model.snapshot_create_response import SnapshotCreateResponse


class TestSnapshotCreateResponse(unittest.TestCase):
    """SnapshotCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotCreateResponse(self):
        """Test SnapshotCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SnapshotCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
