"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_attach_ssh_key_response_error import ManageAttachSshKeyResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageAttachSshKeyResponseError'] = ManageAttachSshKeyResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_attach_ssh_key_response import ManageAttachSshKeyResponse


class TestManageAttachSshKeyResponse(unittest.TestCase):
    """ManageAttachSshKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageAttachSshKeyResponse(self):
        """Test ManageAttachSshKeyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageAttachSshKeyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
