"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.network_create_private_network_response_error import NetworkCreatePrivateNetworkResponseError


class TestNetworkCreatePrivateNetworkResponseError(unittest.TestCase):
    """NetworkCreatePrivateNetworkResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkCreatePrivateNetworkResponseError(self):
        """Test NetworkCreatePrivateNetworkResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkCreatePrivateNetworkResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
