"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.structures_file_info import StructuresFileInfo
globals()['StructuresFileInfo'] = StructuresFileInfo
from vps_generated.model.backup_get_backup_file_list_response import BackupGetBackupFileListResponse


class TestBackupGetBackupFileListResponse(unittest.TestCase):
    """BackupGetBackupFileListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackupGetBackupFileListResponse(self):
        """Test BackupGetBackupFileListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BackupGetBackupFileListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
