"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.snapshot_remove_response_error import SnapshotRemoveResponseError


class TestSnapshotRemoveResponseError(unittest.TestCase):
    """SnapshotRemoveResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotRemoveResponseError(self):
        """Test SnapshotRemoveResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SnapshotRemoveResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
