"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.ssh_key_remove_response_error import SshKeyRemoveResponseError
from vps_generated.model.structures_ssh_key_info import StructuresSshKeyInfo
globals()['SshKeyRemoveResponseError'] = SshKeyRemoveResponseError
globals()['StructuresSshKeyInfo'] = StructuresSshKeyInfo
from vps_generated.model.ssh_key_remove_response import SshKeyRemoveResponse


class TestSshKeyRemoveResponse(unittest.TestCase):
    """SshKeyRemoveResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSshKeyRemoveResponse(self):
        """Test SshKeyRemoveResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SshKeyRemoveResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
