"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_start_rescue_response_error import ManageStartRescueResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageStartRescueResponseError'] = ManageStartRescueResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_start_rescue_response import ManageStartRescueResponse


class TestManageStartRescueResponse(unittest.TestCase):
    """ManageStartRescueResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageStartRescueResponse(self):
        """Test ManageStartRescueResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageStartRescueResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
