"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.snapshot_required_configuration import SnapshotRequiredConfiguration
from vps_generated.model.structures_operating_system import StructuresOperatingSystem
globals()['SnapshotRequiredConfiguration'] = SnapshotRequiredConfiguration
globals()['StructuresOperatingSystem'] = StructuresOperatingSystem
from vps_generated.model.snapshot_snapshot import SnapshotSnapshot


class TestSnapshotSnapshot(unittest.TestCase):
    """SnapshotSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotSnapshot(self):
        """Test SnapshotSnapshot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SnapshotSnapshot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
