"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.statistic_get_process_list_response_process_list_process_info import StatisticGetProcessListResponseProcessListProcessInfo
globals()['StatisticGetProcessListResponseProcessListProcessInfo'] = StatisticGetProcessListResponseProcessListProcessInfo
from vps_generated.model.statistic_get_process_list_response_process_list import StatisticGetProcessListResponseProcessList


class TestStatisticGetProcessListResponseProcessList(unittest.TestCase):
    """StatisticGetProcessListResponseProcessList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatisticGetProcessListResponseProcessList(self):
        """Test StatisticGetProcessListResponseProcessList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatisticGetProcessListResponseProcessList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
