"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.statistic_get_cpu_details_response import StatisticGetCpuDetailsResponse


class TestStatisticGetCpuDetailsResponse(unittest.TestCase):
    """StatisticGetCpuDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatisticGetCpuDetailsResponse(self):
        """Test StatisticGetCpuDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatisticGetCpuDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
