"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_reinstall_response_error_software_variable_error import ManageReinstallResponseErrorSoftwareVariableError
globals()['ManageReinstallResponseErrorSoftwareVariableError'] = ManageReinstallResponseErrorSoftwareVariableError
from vps_generated.model.manage_reinstall_response_error import ManageReinstallResponseError


class TestManageReinstallResponseError(unittest.TestCase):
    """ManageReinstallResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageReinstallResponseError(self):
        """Test ManageReinstallResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageReinstallResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
