"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.network_suggest_private_address_response import NetworkSuggestPrivateAddressResponse


class TestNetworkSuggestPrivateAddressResponse(unittest.TestCase):
    """NetworkSuggestPrivateAddressResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkSuggestPrivateAddressResponse(self):
        """Test NetworkSuggestPrivateAddressResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkSuggestPrivateAddressResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
