"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import vps_generated
from vps_generated.api.statistic_service_api import StatisticServiceApi  # noqa: E501


class TestStatisticServiceApi(unittest.TestCase):
    """StatisticServiceApi unit test stubs"""

    def setUp(self):
        self.api = StatisticServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_statistic_service_get_cpu(self):
        """Test case for statistic_service_get_cpu

        """
        pass

    def test_statistic_service_get_cpu_details(self):
        """Test case for statistic_service_get_cpu_details

        """
        pass

    def test_statistic_service_get_disk(self):
        """Test case for statistic_service_get_disk

        """
        pass

    def test_statistic_service_get_disk_usage(self):
        """Test case for statistic_service_get_disk_usage

        """
        pass

    def test_statistic_service_get_load_average(self):
        """Test case for statistic_service_get_load_average

        """
        pass

    def test_statistic_service_get_memory(self):
        """Test case for statistic_service_get_memory

        """
        pass

    def test_statistic_service_get_network(self):
        """Test case for statistic_service_get_network

        """
        pass

    def test_statistic_service_get_process_list(self):
        """Test case for statistic_service_get_process_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
