"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.structures_additional_ip_info import StructuresAdditionalIpInfo


class TestStructuresAdditionalIpInfo(unittest.TestCase):
    """StructuresAdditionalIpInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStructuresAdditionalIpInfo(self):
        """Test StructuresAdditionalIpInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StructuresAdditionalIpInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
