"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import vps_generated
from vps_generated.api.network_service_api import NetworkServiceApi  # noqa: E501


class TestNetworkServiceApi(unittest.TestCase):
    """NetworkServiceApi unit test stubs"""

    def setUp(self):
        self.api = NetworkServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_network_service_create_private_network(self):
        """Test case for network_service_create_private_network

        """
        pass

    def test_network_service_get_network_info(self):
        """Test case for network_service_get_network_info

        """
        pass

    def test_network_service_order_ip_address(self):
        """Test case for network_service_order_ip_address

        """
        pass

    def test_network_service_remove_ip_address(self):
        """Test case for network_service_remove_ip_address

        """
        pass

    def test_network_service_suggest_private_address(self):
        """Test case for network_service_suggest_private_address

        """
        pass


if __name__ == '__main__':
    unittest.main()
