"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_change_ssh_access_response_error import ManageChangeSshAccessResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageChangeSshAccessResponseError'] = ManageChangeSshAccessResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_change_ssh_access_response import ManageChangeSshAccessResponse


class TestManageChangeSshAccessResponse(unittest.TestCase):
    """ManageChangeSshAccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageChangeSshAccessResponse(self):
        """Test ManageChangeSshAccessResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageChangeSshAccessResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
