"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_get_available_software_response_software_info_requirements import ManageGetAvailableSoftwareResponseSoftwareInfoRequirements


class TestManageGetAvailableSoftwareResponseSoftwareInfoRequirements(unittest.TestCase):
    """ManageGetAvailableSoftwareResponseSoftwareInfoRequirements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageGetAvailableSoftwareResponseSoftwareInfoRequirements(self):
        """Test ManageGetAvailableSoftwareResponseSoftwareInfoRequirements"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageGetAvailableSoftwareResponseSoftwareInfoRequirements()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
