"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.backup_restore_server_response_error import BackupRestoreServerResponseError
from vps_generated.model.structures_order_info import StructuresOrderInfo
globals()['BackupRestoreServerResponseError'] = BackupRestoreServerResponseError
globals()['StructuresOrderInfo'] = StructuresOrderInfo
from vps_generated.model.backup_restore_server_response import BackupRestoreServerResponse


class TestBackupRestoreServerResponse(unittest.TestCase):
    """BackupRestoreServerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackupRestoreServerResponse(self):
        """Test BackupRestoreServerResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BackupRestoreServerResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
