"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.manage_detach_from_private_network_response_error import ManageDetachFromPrivateNetworkResponseError
from vps_generated.model.manage_vps_info import ManageVpsInfo
globals()['ManageDetachFromPrivateNetworkResponseError'] = ManageDetachFromPrivateNetworkResponseError
globals()['ManageVpsInfo'] = ManageVpsInfo
from vps_generated.model.manage_detach_from_private_network_response import ManageDetachFromPrivateNetworkResponse


class TestManageDetachFromPrivateNetworkResponse(unittest.TestCase):
    """ManageDetachFromPrivateNetworkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManageDetachFromPrivateNetworkResponse(self):
        """Test ManageDetachFromPrivateNetworkResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ManageDetachFromPrivateNetworkResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
