"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import vps_generated
from vps_generated.model.structures_additional_ip_info import StructuresAdditionalIpInfo
from vps_generated.model.structures_ip_info import StructuresIpInfo
from vps_generated.model.structures_private_network import StructuresPrivateNetwork
globals()['StructuresAdditionalIpInfo'] = StructuresAdditionalIpInfo
globals()['StructuresIpInfo'] = StructuresIpInfo
globals()['StructuresPrivateNetwork'] = StructuresPrivateNetwork
from vps_generated.model.network_get_network_info_response import NetworkGetNetworkInfoResponse


class TestNetworkGetNetworkInfoResponse(unittest.TestCase):
    """NetworkGetNetworkInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkGetNetworkInfoResponse(self):
        """Test NetworkGetNetworkInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkGetNetworkInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
